#!/usr/bin/env node
/**
 * build-kb.js  —  Generates functions/api/_kb.js from content.json
 * Run:  node build-kb.js
 * Auto: GitHub Actions triggers this before node generate.js on content changes.
 */

const fs   = require('fs');
const path = require('path');

const data = JSON.parse(fs.readFileSync(path.join(__dirname, 'content.json'), 'utf8'));

// Pre-index for O(1) lookups
const pillarMap = new Map(data.pillars.map(p => [p.id, p]));

const lines = [];

lines.push('=== FRQNCY — THE CONSCIOUS LIVING NETWORK ===');
lines.push('FRQNCY is a curated platform mapping the frontier of conscious living.');
lines.push(`It organises ${data.topics.length} Topics across ${data.domains.length} Domains and ${data.pillars.length} Pillars — each with hand-picked resources.`);
lines.push('Website: frqncy.network');
lines.push('');

// Pillars
lines.push('--- PILLARS ---');
for (const p of data.pillars) lines.push(`Pillar: ${p.label} | ${p.desc}`);
lines.push('');

// Domains
lines.push('--- DOMAINS ---');
for (const d of data.domains) {
  const pillar = pillarMap.get(d.pillar);
  lines.push(`Domain: ${d.label} [${pillar ? pillar.label : d.pillar}] | ${d.desc}`);
}
lines.push('');

// Topics grouped by domain — include up to 3 FRQNCY Picks per topic for richer AI context
lines.push('--- TOPICS & FRQNCY PICKS ---');

const topicsByDomain = new Map(data.domains.map(d => [d.id, []]));
for (const t of data.topics) topicsByDomain.get(t.domain)?.push(t);

for (const d of data.domains) {
  const topics = topicsByDomain.get(d.id) || [];
  if (!topics.length) continue;
  lines.push(`\n[${d.label}]`);
  for (const t of topics) {
    const res   = data.resources[t.id] || [];
    const picks = res.filter(r => r.frqncy_pick).slice(0, 3);
    const pickStr = picks.length
      ? ' | PICKS: ' + picks.map(p => `"${p.title}"${p.desc ? ` — ${p.desc}` : ''}`).join('; ')
      : '';
    lines.push(`  • ${t.label}: ${t.desc || ''}${pickStr}`);
  }
}

lines.push('');
lines.push('--- SITE NAVIGATION ---');
lines.push('Home: / | Explore map: /v2/explore.html | Start Here: /start-here.html');
lines.push('About FRQNCY: /about.html | Platform: /platform.html | Podcast: /podcast.html | Space: /space.html');
lines.push('Each topic has its own page at /v2/[topic-slug]/');

const kb = lines.join('\n');

const outPath = path.join(__dirname, 'functions', 'api', '_kb.js');
fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, `// AUTO-GENERATED by build-kb.js — do not edit manually\n// Run: node build-kb.js\n\nexport const KB = ${JSON.stringify(kb)};\n`, 'utf8');

console.log(`✓ Knowledge base → functions/api/_kb.js`);
console.log(`  ${data.pillars.length} pillars · ${data.domains.length} domains · ${data.topics.length} topics`);
console.log(`  ${kb.length.toLocaleString()} chars (~${Math.round(kb.length / 4).toLocaleString()} tokens)`);
