// NRG ↔ Bluesky cross-post bridge.
//
// Per proposals/ATPROTO-BRIDGE.md. Client-side only — the app password never
// touches FRQNCY's server. The user generates an app password at
// https://bsky.app/settings/app-passwords, enters it on the Connections panel,
// and we persist it to localStorage. From then on every NRG post optionally
// gets mirrored to the user's Bluesky PDS via the public AppView.
//
// Storage layout (localStorage, never sent to FRQNCY's server):
//   frqncy.nrg.atproto.handle           — e.g. "alice.bsky.social"
//   frqncy.nrg.atproto.app_password     — 16-char app password (xxxx-xxxx-xxxx-xxxx)
//                                         STORED LOCALLY, NEVER SENT TO FRQNCY's SERVER.
//   frqncy.nrg.atproto.crosspost_default — '1' or '0', user's last toggle state
//
// Why app password, not OAuth: at the time of writing, ATProto OAuth + DPoP
// support in @atproto/api is still in flux. App passwords are a one-shot,
// revocable, scoped credential that every Bluesky user already understands
// from third-party clients. v2 will swap this for the OAuth flow without
// touching publishToBluesky's interface. See proposals/ATPROTO-BRIDGE.md.
//
// Failure mode: a Bluesky outage, expired/revoked app password, or rate-limit
// MUST NOT block an NRG post. publishToBluesky is fire-and-forget from the
// caller's perspective; errors get logged and surfaced via the return value
// only if the caller cares to await it.

const HANDLE_KEY = 'frqncy.nrg.atproto.handle';
const APP_PASSWORD_KEY = 'frqncy.nrg.atproto.app_password';

// Lazily-loaded BskyAgent to avoid importing the SDK on every page (and so
// builds without @atproto/api installed don't crash). The module-level cache
// keys agents by handle so repeated publishToBluesky calls reuse the session.
type AnyAgent = any;
const agentCache = new Map<string, AnyAgent>();

async function loadBskyAgentClass(): Promise<any | null> {
  try {
    // Dynamic import so projects without the dep installed don't fail to
    // build. publishToBluesky / connectBluesky will return ok:false with a
    // descriptive reason instead.
    const mod = await import('@atproto/api');
    return mod.BskyAgent ?? mod.default?.BskyAgent ?? null;
  } catch (err) {
    console.warn('[atproto] @atproto/api import failed — bridge disabled:', err);
    return null;
  }
}

// ─── Connect ────────────────────────────────────────────────────────────────

interface ConnectInput {
  handle: string;
  appPassword: string;
  userId: string;
}

/**
 * Test a handle + app password by attempting a login. On success, persists
 * the handle to profiles.bluesky_handle and the app password to localStorage.
 * On failure, returns the error.
 *
 * App password format: 16 chars in 4 groups of 4 with dashes (xxxx-xxxx-xxxx-xxxx).
 * Generated by the user at https://bsky.app/settings/app-passwords.
 *
 * Note: we DO NOT update profiles.bluesky_handle from this function — the
 * caller (ConnectionsPanel) does that after login succeeds, so the column
 * write goes through Supabase RLS with the user's normal session.
 */
export async function connectBluesky(
  opts: ConnectInput,
): Promise<{ ok: true; did: string } | { ok: false; reason: string }> {
  const handle = normalizeHandle(opts.handle);
  const appPassword = opts.appPassword.trim();

  if (!handle) {
    return { ok: false, reason: 'Enter your Bluesky handle (e.g. alice.bsky.social).' };
  }
  if (!appPassword) {
    return { ok: false, reason: 'Enter an app password (generate one at bsky.app/settings/app-passwords).' };
  }
  // Light shape check — Bluesky app passwords are 19 chars (16 + 3 dashes).
  // We don't hard-fail on shape because the format could change; we just
  // give a friendlier error before the round-trip.
  if (appPassword.length < 12) {
    return { ok: false, reason: 'That doesn\'t look like an app password. Generate one at bsky.app/settings/app-passwords.' };
  }

  const BskyAgent = await loadBskyAgentClass();
  if (!BskyAgent) {
    return { ok: false, reason: 'Bluesky SDK not loaded. Run `npm install @atproto/api` and rebuild.' };
  }

  try {
    const agent = new BskyAgent({ service: 'https://bsky.social' });
    const res = await agent.login({ identifier: handle, password: appPassword });
    if (!res?.success || !res.data?.did) {
      return { ok: false, reason: 'Login returned no DID — check the handle and try again.' };
    }
    // Cache the live agent so the next publishToBluesky call doesn't re-login.
    agentCache.set(handle, agent);
    persistCredentials(handle, appPassword);
    return { ok: true, did: res.data.did };
  } catch (err: any) {
    return { ok: false, reason: translateBskyError(err) };
  }
}

// ─── Publish ────────────────────────────────────────────────────────────────

interface PublishInput {
  text: string;
  nrgPostId?: string;
  appendFooter?: boolean;
}

/**
 * Publish a post to Bluesky on behalf of the connected user. Returns the
 * at-uri of the new post on success.
 *
 * If the user is not connected (no app password in localStorage), returns
 * { ok: false, reason: 'not-connected' }.
 *
 * The post text is the NRG post content. We append a small "via FRQNCY NRG"
 * footer with a link to the NRG post. The footer is opt-out via
 * opts.appendFooter=false.
 */
export async function publishToBluesky(
  opts: PublishInput,
): Promise<{ ok: true; uri: string; cid: string } | { ok: false; reason: string }> {
  if (!isBlueskyConnected()) {
    return { ok: false, reason: 'not-connected' };
  }

  const handle = getConnectedBlueskyHandle();
  const appPassword = getStoredAppPassword();
  if (!handle || !appPassword) {
    return { ok: false, reason: 'not-connected' };
  }

  const text = composePostText(opts.text, opts.nrgPostId, opts.appendFooter !== false);

  const BskyAgent = await loadBskyAgentClass();
  if (!BskyAgent) {
    return { ok: false, reason: 'Bluesky SDK not loaded. Run `npm install @atproto/api` and rebuild.' };
  }

  try {
    let agent = agentCache.get(handle);
    if (!agent) {
      agent = new BskyAgent({ service: 'https://bsky.social' });
      const loginRes = await agent.login({ identifier: handle, password: appPassword });
      if (!loginRes?.success) {
        return { ok: false, reason: 'Bluesky login failed. The app password may have been revoked — reconnect at /social/profile/connections.' };
      }
      agentCache.set(handle, agent);
    }

    const res = await agent.post({
      text,
      createdAt: new Date().toISOString(),
    });
    if (!res?.uri || !res?.cid) {
      return { ok: false, reason: 'Bluesky post returned no URI.' };
    }
    return { ok: true, uri: res.uri, cid: res.cid };
  } catch (err: any) {
    // Drop the cached agent so the next attempt re-logs in with fresh auth.
    agentCache.delete(handle);
    return { ok: false, reason: translateBskyError(err) };
  }
}

// ─── Status helpers ─────────────────────────────────────────────────────────

/** Returns the connected handle (from localStorage) or null. */
export function getConnectedBlueskyHandle(): string | null {
  if (typeof window === 'undefined') return null;
  try {
    return window.localStorage.getItem(HANDLE_KEY);
  } catch {
    return null;
  }
}

/** Returns true if the user has a Bluesky app password in localStorage. */
export function isBlueskyConnected(): boolean {
  if (typeof window === 'undefined') return false;
  try {
    return (
      !!window.localStorage.getItem(HANDLE_KEY) &&
      !!window.localStorage.getItem(APP_PASSWORD_KEY)
    );
  } catch {
    return false;
  }
}

/** Wipes the localStorage app password + handle. Does NOT clear the
    profile's bluesky_handle column (caller decides whether to do that). */
export function disconnectBluesky(): void {
  if (typeof window === 'undefined') return;
  try {
    const handle = window.localStorage.getItem(HANDLE_KEY);
    window.localStorage.removeItem(HANDLE_KEY);
    window.localStorage.removeItem(APP_PASSWORD_KEY);
    if (handle) agentCache.delete(handle);
  } catch {
    // localStorage write can fail in private mode — non-fatal.
  }
}

// ─── Internal helpers ───────────────────────────────────────────────────────

function persistCredentials(handle: string, appPassword: string): void {
  if (typeof window === 'undefined') return;
  try {
    window.localStorage.setItem(HANDLE_KEY, handle);
    window.localStorage.setItem(APP_PASSWORD_KEY, appPassword);
  } catch (err) {
    console.warn('[atproto] failed to persist credentials to localStorage:', err);
  }
}

function getStoredAppPassword(): string | null {
  if (typeof window === 'undefined') return null;
  try {
    return window.localStorage.getItem(APP_PASSWORD_KEY);
  } catch {
    return null;
  }
}

function normalizeHandle(raw: string): string {
  return raw.trim().toLowerCase().replace(/^@/, '');
}

const BLUESKY_TEXT_LIMIT = 300;

function composePostText(
  body: string,
  nrgPostId: string | undefined,
  appendFooter: boolean,
): string {
  const trimmedBody = body.trim();
  if (!appendFooter) {
    return truncateGraphemes(trimmedBody, BLUESKY_TEXT_LIMIT);
  }

  const link = nrgPostId
    ? `https://frqncy.network/social/posts/${nrgPostId}`
    : 'https://frqncy.network';
  const footer = `\n\n— via FRQNCY NRG ↗\n${link}`;

  // Reserve room for the footer; truncate the body portion only.
  const footerLen = countGraphemes(footer);
  const room = BLUESKY_TEXT_LIMIT - footerLen;
  if (room <= 0) {
    // Footer alone exceeds the limit — defensive; should never happen with
    // the canonical FRQNCY URL. Just send the body, no footer.
    return truncateGraphemes(trimmedBody, BLUESKY_TEXT_LIMIT);
  }
  const fittedBody = truncateGraphemes(trimmedBody, room);
  return fittedBody + footer;
}

/** Approximate grapheme count — Bluesky's official limit is graphemes, but
    a precise count requires Intl.Segmenter (modern browsers only). We use
    Intl.Segmenter when available and fall back to Array.from(str).length
    (correctly counts surrogate pairs but not all combining marks). */
function countGraphemes(s: string): number {
  if (typeof Intl !== 'undefined' && (Intl as any).Segmenter) {
    try {
      const seg = new (Intl as any).Segmenter('en', { granularity: 'grapheme' });
      let n = 0;
      for (const _ of seg.segment(s)) n++;
      return n;
    } catch {
      // fall through
    }
  }
  return Array.from(s).length;
}

function truncateGraphemes(s: string, maxGraphemes: number): string {
  if (countGraphemes(s) <= maxGraphemes) return s;
  // We need room for an ellipsis (1 grapheme).
  const targetCount = Math.max(1, maxGraphemes - 1);
  if (typeof Intl !== 'undefined' && (Intl as any).Segmenter) {
    try {
      const seg = new (Intl as any).Segmenter('en', { granularity: 'grapheme' });
      const out: string[] = [];
      for (const part of seg.segment(s)) {
        if (out.length >= targetCount) break;
        out.push(part.segment);
      }
      return out.join('') + '…';
    } catch {
      // fall through
    }
  }
  const arr = Array.from(s);
  return arr.slice(0, targetCount).join('') + '…';
}

function translateBskyError(err: any): string {
  const msg = (err?.message || err?.error || String(err || '')).toLowerCase();
  if (!msg) return 'Bluesky request failed (no message). Check the network and try again.';
  if (msg.includes('invalid') && (msg.includes('password') || msg.includes('credentials'))) {
    return 'Invalid handle or app password. Generate a fresh one at bsky.app/settings/app-passwords.';
  }
  if (msg.includes('rate') && msg.includes('limit')) {
    return 'Bluesky rate-limited the request. Try again in a minute.';
  }
  if (msg.includes('network') || msg.includes('failed to fetch') || msg.includes('fetch failed')) {
    return 'Network error reaching Bluesky. Check your connection and try again.';
  }
  if (msg.includes('account') && msg.includes('not') && msg.includes('found')) {
    return 'No Bluesky account found for that handle.';
  }
  // Surface the raw message — cleaned up — as a fallback.
  return `Bluesky error: ${err?.message || 'unknown'}`;
}
