/* empty css                                        */
import { c as createComponent, r as renderComponent, a as renderTemplate, b as createAstro, m as maybeRenderHead } from '../../chunks/astro/server_C8GjfOXF.mjs';
import 'piccolore';
import 'html-escaper';
import { $ as $$SocialLayout } from '../../chunks/SocialLayout_BQoA4DU3.mjs';
export { renderers } from '../../renderers.mjs';

const $$Astro = createAstro();
const $$Roadmap = createComponent(($$result, $$props, $$slots) => {
  const Astro2 = $$result.createAstro($$Astro, $$props, $$slots);
  Astro2.self = $$Roadmap;
  return renderTemplate`${renderComponent($$result, "SocialLayout", $$SocialLayout, { "title": "Roadmap", "description": "The 24-month roadmap for FRQNCY Social \u2014 from centralized MVP to a protocol-native community network." }, { "default": ($$result2) => renderTemplate` ${maybeRenderHead()}<article class="max-w-4xl mx-auto mt-8 space-y-12 pb-16"> <!-- Header --> <header class="space-y-4"> <p class="text-xs uppercase tracking-[0.25em] text-gold/70 font-body">Space / Roadmap</p> <h1 class="font-heading text-4xl md:text-5xl text-gold leading-tight">
Building FRQNCY Social
</h1> <p class="text-lg text-text-dim leading-relaxed max-w-3xl">
A 24-month plan to take FRQNCY from a centralized MVP to a protocol-native community network — on the destination axis of Farcaster and Nostr, but routed through AT Protocol because that's where the audience already is.
</p> <div class="flex flex-wrap gap-2 pt-2"> <span class="text-xs px-3 py-1 rounded-full bg-gold/10 border border-gold/30 text-gold">Living document</span> <span class="text-xs px-3 py-1 rounded-full bg-navy-mid border border-card-border text-text-dim">v1 · April 2026</span> </div> </header> <!-- TL;DR --> <section class="rounded-2xl bg-gradient-to-br from-gold/5 to-accent/5 border border-gold/20 p-8 space-y-4"> <h2 class="font-heading text-2xl text-gold">TL;DR</h2> <p class="text-text-dim leading-relaxed">
FRQNCY Social is a small, values-driven, crypto-adjacent community network. Today it is a centralized app on Supabase + Astro + Preact. In 24 months it is an AT Protocol-native app with a Farcaster side-channel for crypto surfaces and a Nostr read-bridge. The bet: <span class="text-text">lean chronological feed, follow-graph primary, transparent re-ranker, project-anchored conversation as the headline differentiator</span>, monetized by freemium + tipping — no ads, ever. Cooperation, not competition — no public leaderboards.
</p> <div class="pt-2"> <a href="/social/space/research" class="text-sm text-gold hover:text-gold-light transition-colors underline decoration-gold/40 hover:decoration-gold">
Read the full research paper →
</a> </div> </section> <!-- Phase 1 --> <section class="space-y-6"> <div class="flex items-baseline gap-4 border-b border-card-border pb-3"> <span class="font-heading text-5xl text-gold/20">01</span> <div> <h2 class="font-heading text-3xl text-gold">Phase 1 — Centralized, Portable Bones</h2> <p class="text-sm text-text-dim mt-1">Months 0 – 6 · Where we are today</p> </div> </div> <p class="text-text-dim leading-relaxed">
Keep the Supabase + Astro + Preact stack exactly as it is. Use this phase to nail product-market fit on a tight community before any protocol work lands in production. Shipping discipline beats architectural purity.
</p> <div class="grid md:grid-cols-3 gap-4"> <div class="rounded-xl bg-card-bg border border-card-border p-5 space-y-3"> <h3 class="font-heading text-lg text-gold">Protocol</h3> <ul class="space-y-2 text-sm text-text-dim"> <li class="flex gap-2"><span class="text-gold mt-1">✓</span><span>Supabase source of truth</span></li> <li class="flex gap-2"><span class="text-gold mt-1">✓</span><span>Auth, posts, follows, DMs, comments</span></li> <li class="flex gap-2"><span class="text-text-dim/60 mt-1">○</span><span>Lexicon spec repo <code class="text-xs text-gold">xyz.frqncy.*</code></span></li> <li class="flex gap-2"><span class="text-text-dim/60 mt-1">○</span><span>Lazy <code class="text-xs text-gold">did:web</code> per user</span></li> <li class="flex gap-2"><span class="text-text-dim/60 mt-1">○</span><span>Nightly signed-JSON export</span></li> </ul> </div> <div class="rounded-xl bg-card-bg border border-card-border p-5 space-y-3"> <h3 class="font-heading text-lg text-gold">Ranking</h3> <ul class="space-y-2 text-sm text-text-dim"> <li class="flex gap-2"><span class="text-gold mt-1">✓</span><span>Reverse-chrono feed</span></li> <li class="flex gap-2"><span class="text-gold mt-1">✓</span><span>Profile feed filter</span></li> <li class="flex gap-2"><span class="text-text-dim/60 mt-1">○</span><span>Project-anchored rooms</span></li> <li class="flex gap-2"><span class="text-text-dim/60 mt-1">○</span><span>Points-only conviction v1</span></li> <li class="flex gap-2"><span class="text-text-dim/60 mt-1">○</span><span>Full ranking formula behind flag</span></li> </ul> </div> <div class="rounded-xl bg-card-bg border border-card-border p-5 space-y-3"> <h3 class="font-heading text-lg text-gold">Economics</h3> <ul class="space-y-2 text-sm text-text-dim"> <li class="flex gap-2"><span class="text-gold mt-1">✓</span><span>Free core product</span></li> <li class="flex gap-2"><span class="text-red-400/70 mt-1">✗</span><span>No ads — ever</span></li> <li class="flex gap-2"><span class="text-text-dim/60 mt-1">○</span><span>$5/mo Supporter tier</span></li> <li class="flex gap-2"><span class="text-text-dim/60 mt-1">○</span><span>Stripe Connect tipping</span></li> <li class="flex gap-2"><span class="text-text-dim/60 mt-1">○</span><span>Llama Guard 3 moderation pass</span></li> </ul> </div> </div> </section> <!-- Phase 2 --> <section class="space-y-6"> <div class="flex items-baseline gap-4 border-b border-card-border pb-3"> <span class="font-heading text-5xl text-gold/20">02</span> <div> <h2 class="font-heading text-3xl text-gold">Phase 2 — Dual-Write Federation</h2> <p class="text-sm text-text-dim mt-1">Months 6 – 12 · Differentiation lock-in</p> </div> </div> <p class="text-text-dim leading-relaxed">
Stand up a production PDS serving <code class="text-sm text-gold">*.frqncy.social</code>, dual-write every post / follow / like to the user's signed repo, consume the Bluesky firehose via Jetstream, and run a custom App View on Cloudflare Workers + D1. The reputation vector (Social, Conviction, Debate) replaces the scalar karma number on profiles.
</p> <div class="grid md:grid-cols-3 gap-4"> <div class="rounded-xl bg-card-bg border border-card-border p-5 space-y-3"> <h3 class="font-heading text-lg text-gold">Protocol</h3> <ul class="space-y-2 text-sm text-text-dim"> <li>Production PDS</li> <li>Jetstream firehose ingest</li> <li>Custom App View</li> <li>Cross-post to Bluesky</li> <li>Cross-post to Farcaster (Neynar)</li> <li>In-house Ozone labeler</li> </ul> </div> <div class="rounded-xl bg-card-bg border border-card-border p-5 space-y-3"> <h3 class="font-heading text-lg text-gold">Ranking</h3> <ul class="space-y-2 text-sm text-text-dim"> <li>Discover surface (interest-graph)</li> <li>Contribution signals on profile (posts, replies, helpful tags)</li> <li>Project-anchored rooms w/ shared context</li> <li>Weekly "projects to revisit" digest</li> <li>A/B test ranking weights transparently</li> </ul> </div> <div class="rounded-xl bg-card-bg border border-card-border p-5 space-y-3"> <h3 class="font-heading text-lg text-gold">Economics</h3> <ul class="space-y-2 text-sm text-text-dim"> <li>NFT Founding Member (500 seats)</li> <li>Tipping fee 0% → 3%</li> <li>Trust-level system (TL0–TL4)</li> <li>Community mods per channel</li> <li>Crypto-attorney review of v2 markets</li> </ul> </div> </div> </section> <!-- Phase 3 --> <section class="space-y-6"> <div class="flex items-baseline gap-4 border-b border-card-border pb-3"> <span class="font-heading text-5xl text-gold/20">03</span> <div> <h2 class="font-heading text-3xl text-gold">Phase 3 — Protocol-Native</h2> <p class="text-sm text-text-dim mt-1">Months 12 – 24 · Platform-optional</p> </div> </div> <p class="text-text-dim leading-relaxed">
Flip the source of truth: PDS records are canonical, Supabase demotes to index / cache. Users can bring their own DID, export their repo, move to another PDS host without losing followers. Publish the FRQNCY Lexicons so <em>any</em> ATProto client can consume <code class="text-sm text-gold">xyz.frqncy.resonance</code>. Ship a Farcaster Mini App for the 630-project rating surface. The network outlives the app.
</p> <div class="grid md:grid-cols-3 gap-4"> <div class="rounded-xl bg-card-bg border border-card-border p-5 space-y-3"> <h3 class="font-heading text-lg text-gold">Protocol</h3> <ul class="space-y-2 text-sm text-text-dim"> <li>PDS becomes canonical</li> <li>BYO-DID import</li> <li>Public Lexicon registry</li> <li>Farcaster Mini App</li> <li>Nostr read-bridge</li> </ul> </div> <div class="rounded-xl bg-card-bg border border-card-border p-5 space-y-3"> <h3 class="font-heading text-lg text-gold">Ranking</h3> <ul class="space-y-2 text-sm text-text-dim"> <li>FRQNCY ranker as Bluesky custom feed</li> <li>User-facing feed-tuning sliders</li> <li>Opt-in AI personal feeds</li> <li>Reputation as portable PDS record</li> </ul> </div> <div class="rounded-xl bg-card-bg border border-card-border p-5 space-y-3"> <h3 class="font-heading text-lg text-gold">Economics</h3> <ul class="space-y-2 text-sm text-text-dim"> <li>Staked markets — only if legal-cleared and community-aligned</li> <li>Private personal conviction journal (no public ranking)</li> <li>Per-channel mod rotation (6 mo)</li> <li>Public transparency report</li> </ul> </div> </div> </section> <!-- Non-negotiables --> <section class="rounded-2xl bg-card-bg border border-card-border p-8 space-y-4"> <h2 class="font-heading text-2xl text-gold">Non-Negotiables</h2> <ul class="space-y-3 text-text-dim"> <li class="flex gap-3"> <span class="text-gold font-heading text-lg leading-none">·</span> <span><strong class="text-text">No ads, ever.</strong> Attention that heals, not attention that extracts.</span> </li> <li class="flex gap-3"> <span class="text-gold font-heading text-lg leading-none">·</span> <span><strong class="text-text">Points-only conviction at launch.</strong> No real-money markets until an attorney signs off.</span> </li> <li class="flex gap-3"> <span class="text-gold font-heading text-lg leading-none">·</span> <span><strong class="text-text">Portable by design.</strong> Every user can export their whole repo from day one.</span> </li> <li class="flex gap-3"> <span class="text-gold font-heading text-lg leading-none">·</span> <span><strong class="text-text">Transparent ranking.</strong> The formula ships in docs and as a tuning UI.</span> </li> <li class="flex gap-3"> <span class="text-gold font-heading text-lg leading-none">·</span> <span><strong class="text-text">Blameless post-mortems.</strong> Public write-ups when moderation fails.</span> </li> </ul> </section> <!-- What you can do --> <section class="space-y-4"> <h2 class="font-heading text-2xl text-gold">How to Shape This Roadmap</h2> <p class="text-text-dim leading-relaxed">
This is a living document. The roadmap gets updated when the product learns something — not on a fixed cadence. If you want to influence what ships next, the highest-leverage things you can do are:
</p> <div class="grid md:grid-cols-2 gap-4 pt-2"> <a href="/social" class="group rounded-xl bg-card-bg border border-card-border p-5 hover:border-gold/40 transition-colors"> <h3 class="font-heading text-lg text-gold group-hover:text-gold-light transition-colors">Post and react in the Feed</h3> <p class="text-sm text-text-dim mt-2">Every post, follow, and like is signal for what the network is for. Seed the ritual.</p> </a> <a href="/social/space" class="group rounded-xl bg-card-bg border border-card-border p-5 hover:border-gold/40 transition-colors"> <h3 class="font-heading text-lg text-gold group-hover:text-gold-light transition-colors">Explore the Space</h3> <p class="text-sm text-text-dim mt-2">Read the research, the principles, and the open questions driving FRQNCY Social.</p> </a> <a href="https://github.com/frqncy" target="_blank" rel="noopener" class="group rounded-xl bg-card-bg border border-card-border p-5 hover:border-gold/40 transition-colors"> <h3 class="font-heading text-lg text-gold group-hover:text-gold-light transition-colors">Contribute on GitHub</h3> <p class="text-sm text-text-dim mt-2">The code is open. Issues, PRs, and Lexicon proposals welcome.</p> </a> <a href="mailto:hello@frqncy.network?subject=Roadmap%20feedback" class="group rounded-xl bg-card-bg border border-card-border p-5 hover:border-gold/40 transition-colors"> <h3 class="font-heading text-lg text-gold group-hover:text-gold-light transition-colors">Send feedback</h3> <p class="text-sm text-text-dim mt-2">One email. What's missing, what's wrong, what you wish we'd build next.</p> </a> </div> </section> <!-- Footer --> <footer class="border-t border-card-border pt-8 text-sm text-text-dim"> <p>
Last updated April 18, 2026. Based on the
<a href="/social/space/research" class="text-gold hover:text-gold-light underline decoration-gold/40">
FRQNCY Social research paper
</a>
synthesizing protocol choice, feed ranking, and monetization research. Informed by nine parallel research and build agents, April 2026.
</p> </footer> </article> ` })}`;
}, "/sessions/relaxed-keen-euler/mnt/FRQNCY WEBSITE/social/src/pages/space/roadmap.astro", void 0);

const $$file = "/sessions/relaxed-keen-euler/mnt/FRQNCY WEBSITE/social/src/pages/space/roadmap.astro";
const $$url = "/social/space/roadmap";

const _page = /*#__PURE__*/Object.freeze(/*#__PURE__*/Object.defineProperty({
  __proto__: null,
  default: $$Roadmap,
  file: $$file,
  url: $$url
}, Symbol.toStringTag, { value: 'Module' }));

const page = () => _page;

export { page };
