#!/usr/bin/env node
// sync-headers.mjs — propagate the canonical _chrome/global-header.html
// into every bespoke (non-generator-driven) page on the site. Pages
// generated by generate.js, scripts/generate_topic_page.py,
// generate-courses.js, and generate-watch.js read the same file directly
// at build time, so they're handled by those generators rather than here.
//
// Usage: node scripts/sync-headers.mjs [--check]
//   default mode: rewrite each target page in place
//   --check     : exit 1 if any target diverges from canonical (CI guard)

import fs from 'node:fs';
import path from 'node:path';

const CANONICAL = fs.readFileSync('_chrome/global-header.html', 'utf8').trimEnd();
const START = '<!-- ▼▼ FRQNCY_GLOBAL_HEADER';
const END   = '<!-- ▲▲ FRQNCY_GLOBAL_HEADER ▲▲ -->';

// Bespoke (hand-edited) pages — generator-driven pages are skipped.
const TARGETS = [
  'index.html',
  'about.html',
  'platform.html',
  'search.html',
  'chart.html',
  'my-frqncy.html',
  'start-here.html',
  'podcast.html',
  'space.html',
  '404.html',
  'membership/index.html',
  'social/index.html',
  'aligned/index.html',
  'v2/watch/index.html',
  'v2/explore.html',
  'v2/fund/index.html',
  'v2/crypto/index.html',
  'v2/crypto/projects.html',
  'v2/crypto/explorer.html',
  'v2/audio/index.html',
  'v2/courses/index.html',
  'v2/network-state/index.html',
  'my-frqncy/dashboard/index.html',
  'my-frqncy/charts/index.html',
  'my-frqncy/practice/index.html',
  // Standalone & social pages (added 2026-05-12 — were running their own
  // bespoke navs and falling out of sync with the canonical header).
  'ask/index.html',
  'editorial-standards/index.html',
  'mcp/index.html',
  'social/login/index.html',
  'social/profile/index.html',
  'social/notifications/index.html',
  'social/messages/index.html',
  'social/search/index.html',
  'social/bookmarks/index.html',
  'social/space/index.html',
  'social/space/research/index.html',
  'social/space/roadmap/index.html',
  'chart-v2/calibration.html',
];

// Course pages — generated by generate-courses.js, but its template doesn't
// (yet) read from _chrome/global-header.html. Sync them after each regen.
try {
  for (const d of fs.readdirSync('v2/courses', { withFileTypes: true })) {
    if (d.isDirectory()) {
      const p = `v2/courses/${d.name}/index.html`;
      if (fs.existsSync(p)) TARGETS.push(p);
    }
  }
} catch (_) { /* v2/courses/ doesn't exist yet — skip */ }

// Bespoke domain pages (15) — hand-shaped, locked from generate.js regen via
// BESPOKE_DOMAINS, so they need direct sync.
for (const slug of ['money','wellbeing','consciousness','sciences','nature','lifestyle','business','energy','food','society','communication','technology','creation','arts','play']) {
  const p = `v2/${slug}/index.html`;
  if (fs.existsSync(p)) TARGETS.push(p);
}

// Patterns for legacy nav blocks we can find + replace with canonical.
// Tried in order. If none match, we insert canonical right after <body...>
// and emit a warning so a human can clean up the page.
const REPLACERS = [
  // already wired with our markers — clean swap
  { name: 'markered', re: new RegExp(`${escapeRe(START)}[\\s\\S]*?${escapeRe(END)}`, 'm') },
  // existing #main-nav (homepage + a few hubs) — replace whole <nav>
  { name: 'main-nav', re: /<nav id="main-nav"[\s\S]*?<\/nav>/m },
  // existing class="snav" — replace whole <nav>
  { name: 'snav',     re: /<nav class="snav"[\s\S]*?<\/nav>/m },
  // existing topic/explore "snav" with extra classes
  { name: 'snav-x',   re: /<nav class="snav[^"]*"[\s\S]*?<\/nav>/m },
];

let changed = 0, inserted = 0, skipped = 0, divergent = 0;
const check = process.argv.includes('--check');

for (const rel of TARGETS) {
  if (!fs.existsSync(rel)) { skipped++; continue; }
  const src = fs.readFileSync(rel, 'utf8');
  let next = null;
  let matched = null;
  for (const r of REPLACERS) {
    if (r.re.test(src)) {
      next = src.replace(r.re, CANONICAL);
      matched = r.name;
      break;
    }
  }
  if (next === null) {
    // No nav at all — inject after the opening <body> tag.
    const bodyOpen = src.match(/<body[^>]*>/);
    if (!bodyOpen) {
      console.warn(`  ⚠️  ${rel}: no <body> tag found — skipped`);
      skipped++; continue;
    }
    const at = bodyOpen.index + bodyOpen[0].length;
    next = src.slice(0, at) + '\n' + CANONICAL + '\n' + src.slice(at);
    matched = 'inserted';
  }
  if (next === src) { skipped++; continue; }
  if (check) {
    console.log(`  ⌐  ${rel} would change (${matched})`);
    divergent++;
    continue;
  }
  fs.writeFileSync(rel, next);
  if (matched === 'inserted') {
    inserted++;
    console.log(`  +  ${rel}  (inserted — verify placement)`);
  } else {
    changed++;
    console.log(`  ✓  ${rel}  (${matched})`);
  }
}

if (check) {
  if (divergent) {
    console.error(`\n✗ ${divergent} page(s) diverge from canonical header.`);
    process.exit(1);
  }
  console.log(`\n✓ all ${TARGETS.length} pages match canonical.`);
} else {
  console.log(`\n✓ synced canonical header → ${changed} replaced, ${inserted} inserted, ${skipped} unchanged/skipped`);
}

function escapeRe(s) { return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'); }
